version: "3"
services:
  app:
    build: .
    command: pm2-dev ./build/src/server.js
    environment:
      NODE_ENV: production
      PORT: 8080
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - ./node_modules:/home/nodejs/node_modules

  nginx:
    image: nginx:latest
    links:
      - app
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
